import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card/Card";
import Footer from "../components/Footer/Footer";
import {
  Container,
  Description,
  Grid,
  Link,
  Main,
  SubTitle,
  Title,
} from "../components/style";
import { PROJECTS } from "../projects";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Aimen Hamed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <div>
          <Title>
            Hello 👋🏻 <br />
            My name is Aimen Hamed.
          </Title>
          <Description>
            I am a <b>Software Engineer</b> at <b>Atlassian</b>. Previously, a
            Platform Engineer at <b>Zip</b>, and Software Engineer at{" "}
            <b>Optus</b>. <br />I love creating developer friendly tools, and
            everything web.
          </Description>
          <Description style={{ margin: "0 0 4rem" }}>
            You can find me on{" "}
            <Link href="https://github.com/aimenhamed">GitHub</Link> and{" "}
            <Link href="https://www.linkedin.com/in/aimen-hamed/">
              Linkedin
            </Link>
            .
          </Description>
          <SubTitle>Projects</SubTitle>
          <Grid>
            {PROJECTS.map((project) => (
              <Card key={project.id} {...project} />
            ))}
          </Grid>
        </div>
      </Main>
      <Footer />
    </Container>
  );
};

export default Home;
